package:
  name: vtk-openvr
  version: "8.1.1"

source:
  fn: VTK-8.1.1.tar.gz
  url: https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz
  sha1: 1b852f4d578d1fb1e79dd046d2d8c4b8206dfa58

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - hdf5

  run:
   - python
   - hdf5

test:
  requires:
    - numpy
    - pillow

  imports:
    - vtk

about:
  home: http://www.vtk.org
  license: BSD
